server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000

stream-server:
  heartbeat-timeout: 60

stream:
  rtmp-url: rtmp://localhost/livestream
  proxy-http-port: 8082