# SRS Proxy Config
# 统一入口，转发推流和拉流
listen 1935;
server_id 2;

# HTTP API
http_api {
    enabled         on;
    listen          1986;
}

# HTTP 服务器
http_server {
    enabled         on;
    listen          8081;
    dir             ./objs/nginx/html;
}

# Vhost 配置
vhost __defaultVhost__ {
    # 作为代理/转发器
    cluster {
        mode             ofl;
        origin           srs-origin:1935;
    }

    # HLS 配置
    hls {
        enabled         on;
        dispose         30;
    }

    # HTTP-FLV 配置
    http_remux {
        enabled         on;
        mount           [vhost]/[app]/[stream].flv;
    }
}