plugins {
    id 'com.android.library'
}

android {
    namespace 'cn.livestream.android'
    compileSdk 34

    defaultConfig {
        minSdk 24
        targetSdk 34
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.android.exoplayer:exoplayer-core:1.2.1'
    implementation 'com.google.android.exoplayer:exoplayer-hls:1.2.1'
}